### PR TITLE
Put "how-to" guides in a blog post form

### PR DESCRIPTION
**Pull request by jdossgollin**
I'd appreciate your feedback @yuchenluv @js336rice

### CODE REVIEW

**Comment by jdossgollin** [comment]
@js336rice @yuchenluv feedback appreciated

**Comment by jdossgollin** [comment]
For a full preview you can open the pull request on git on your computer and then `quarto preview .` to examine it. For example you can open it locally like this

Screenshot 2024-07-03 at 10 23 03 PM

Here's what this looks like in a few screenshots, though

Screenshot 2024-07-03 at 10 23 51 PM

Screenshot 2024-07-03 at 10 24 30 PM

Screenshot 2024-07-03 at 10 24 59 PM

**Comment by js336rice** [comment]
I think it looks good!  Although I think it’d be better if instead of a 3
wide grid, each article was on its own line.  That way people could scan
with their eyes from top to bottom more easily.

Best,
Jonah

**Comment by jdossgollin** [comment]
Screenshot 2024-07-04 at 11 22 59 PM

@js336rice you prefer like this?

**Comment by js336rice** [comment]
Yeah, that looks good!

**Comment by yuchenluv** [comment]
This looks great! Not for now, but I think some posts, like the 'welcome aboard' one, could be pinned at the top later when more posts are available.

**Pull request merged**
